linux_task:
  container:
    image: ubuntu:latest
  env:
    GOPROXY: https://proxy.golang.org
    GOPATH: /tmp/go
    PATH: ${GOPATH}/bin:${PATH}
    CIRRUS_WORKING_DIR: /tmp/go/src/github.com/${CIRRUS_REPO_FULL_NAME}
  install_script:
    - apt-get update && apt-get install --reinstall software-properties-common -y
    - add-apt-repository ppa:longsleep/golang-backports
    - apt-get update && apt-get install git golang-go -y
  clone_script: |
    if [[ -z "$CIRRUS_PR" ]]; then
      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git ${CIRRUS_WORKING_DIR}
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git ${CIRRUS_WORKING_DIR}
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi
  build_script:
    - go version
    - go build -race -v ./...
  test_script:
    - go test -race -v ./...

osx_task:
  osx_instance:
    image: mojave-base
  env:
    GOPROXY: https://proxy.golang.org
    GOPATH: /tmp/go
    PATH: ${GOPATH}/bin:${PATH}
    CIRRUS_WORKING_DIR: /tmp/go/src/github.com/${CIRRUS_REPO_FULL_NAME}
  install_script:
    - brew install git go
  clone_script: |
    if [[ -z "$CIRRUS_PR" ]]; then
      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git ${CIRRUS_WORKING_DIR}
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git ${CIRRUS_WORKING_DIR}
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi
  build_script:
    - go version
    - go build -race -v ./...
  test_script:
    - go test -race -v ./...

windows_task:
  windows_container:
    image: golang:windowsservercore-1803
    os_version: 1803
  env:
    GOPROXY: https://proxy.golang.org
    GOPATH: C:\go
    PATH: ${GOPATH}\bin:${PATH}
    CIRRUS_WORKING_DIR: C:\go\src\github.com\${CIRRUS_REPO_FULL_NAME}
  build_script:
    - go version
    - go build -race -v ./...
  test_script:
    - go test -race -v ./...

freebsd_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  env:
    GOPROXY: https://proxy.golang.org
    GOPATH: /tmp/go
    PATH: ${GOPATH}/bin:${PATH}
    CIRRUS_WORKING_DIR: /tmp/go/src/github.com/${CIRRUS_REPO_FULL_NAME}
  install_script:
    - pkg install -y git go
  clone_script: |
    if ( "$CIRRUS_PR" == "" || ! $?CIRRUS_PR ) then
      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git ${CIRRUS_WORKING_DIR}
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git ${CIRRUS_WORKING_DIR}
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi
  build_script:
    - go version
    - go build -race -v ./...
  test_script:
    - go test -race -v ./...
