linux_task:
  container:
    image: golang:latest
  env:
    GOPROXY: https://proxy.golang.org
    GOPATH: /tmp/go
    CIRRUS_WORKING_DIR: /tmp/go/src/github.com/${CIRRUS_REPO_FULL_NAME}
  build_script:
    - go version
    - go get ./...
    - go build -race -v ./...
  test_script:
    - go test -race -v ./...
  benchmark_script:
    - go test -run=XXX -bench=. .

osx_task:
  osx_instance:
    image: mojave-base
  env:
    GOPROXY: https://proxy.golang.org
    GOPATH: /tmp/go
    PATH: ${GOPATH}/bin:${PATH}
    CIRRUS_WORKING_DIR: /tmp/go/src/github.com/${CIRRUS_REPO_FULL_NAME}
  install_script:
    - brew install go
  build_script:
    - go version
    - go get ./...
    - go build -race -v ./...
  test_script:
    - go test -race -v ./...
  benchmark_script:
    - go test -run=XXX -bench=. .

windows_task:
  windows_container:
    image: golang:windowsservercore-1803
    os_version: 1803
  env:
    GOPROXY: https://proxy.golang.org
    GOPATH: C:\go
    PATH: ${GOPATH}\bin:${PATH}
    CIRRUS_WORKING_DIR: C:\go\src\github.com\${CIRRUS_REPO_FULL_NAME}
  build_script:
    - go version
    - go get ./...
    - go build -race -v ./...
  test_script:
    - go test -race -v ./...
  benchmark_script:
    - go test -run=XXX -bench=. .

freebsd_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  env:
    GOPROXY: https://proxy.golang.org
    GOPATH: /tmp/go
    PATH: ${GOPATH}/bin:${PATH}
    CIRRUS_WORKING_DIR: /tmp/go/src/github.com/${CIRRUS_REPO_FULL_NAME}
  install_script:
    - pkg install -y go
  build_script:
    - go version
    - go get ./...
    - go build -race -v ./...
  test_script:
    - go test -race -v ./...
  benchmark_script:
    - go test -run=XXX -bench=. .
